export const mockWorkflow = [
  { key: "anfrage", label: "Anfrage" },
  { key: "vorgespraech", label: "Vorgespräch" },
  { key: "angebot", label: "Angebot" },
  { key: "vertrag", label: "Vertrag" },
  { key: "anzahlung", label: "Anzahlung" },
  { key: "shooting", label: "Shooting/Hochzeit" },
  { key: "editing", label: "Editing" },
  { key: "galerie", label: "Galerie geliefert" },
  { key: "abgeschlossen", label: "Abgeschlossen" },
] as const;

export const mockMailTemplates = {
  reply: {
    label: "Anfrage beantworten",
    subject: "Danke für deine Anfrage, {firstName}",
    body: "Servus {firstName},\n\nvielen Dank für deine Anfrage. Ich freue mich, mehr über eure Pläne zu erfahren.\n\nIch melde mich zeitnah mit ein paar Terminvorschlägen für ein kurzes Vorgespräch.\n\n{signature}",
  },
  consultation: {
    label: "Vorgespräch",
    subject: "Unser Vorgespräch",
    body: "Servus {firstName},\n\nhier findest du die Details für unser Vorgespräch:\n\nTermin: {consultationDate}\n\nFalls sich bei dir etwas ändert, gib mir einfach kurz Bescheid.\n\n{signature}",
  },
  contract: {
    label: "Vertrag senden",
    subject: "Dein Vertrag mit Mario Schubert Photography",
    body: "Servus {firstName},\n\nich habe dir den Vertrag für euren Termin vorbereitet.\n\nDu findest ihn hier:\n{contractUrl}\n\nWenn alles passt, gib mir bitte kurz Bescheid oder sende mir den unterschriebenen Vertrag zurück.\n\n{signature}",
  },
  portal: {
    label: "Kundenportal",
    subject: "Dein Kundenbereich bei Mario Schubert Photography",
    body: "Servus {firstName},\n\nich habe dir einen persönlichen Kundenbereich eingerichtet. Dort findest du eure gebuchten Leistungen, Termine, Dokumente und später auch den Galerie-Link.\n\n{portalUrl}\n\n{signature}",
  },
  gallery: {
    label: "Galerie geliefert",
    subject: "Eure Galerie ist fertig",
    body: "Servus {firstName},\n\neure Galerie ist fertig. Du findest sie hier:\n{galleryUrl}\n\nIch wünsche euch ganz viel Freude mit den Bildern.\n\n{signature}",
  },
};

export const mockInquiries = [
  {
    id: "mock-inq-1",
    createdAt: "2026-05-15T11:20:00.000Z",
    status: "neu",
    name: "Anna & Lukas Weber",
    brideName: "Anna Weber",
    groomName: "Lukas Weber",
    email: "anna.weber@example.com",
    phone: "+43 660 1234567",
    category: "Hochzeit, Hochzeit Foto",
    eventDate: "2026-09-12",
    foundVia: "Instagram",
    customerAddress: "Musterstraße 12, 6020 Innsbruck",
    locationAddress: "Seehotel am Achensee, Achenseestraße 10, 6212 Maurach",
    locations: [
      { id: "loc-ceremony", title: "Freie Trauung", address: "Wiese am See, Achensee" },
      { id: "loc-party", title: "Feier", address: "Seehotel am Achensee, Achenseestraße 10, 6212 Maurach" },
    ],
    message:
      "Wir feiern im September am Achensee und suchen eine natürliche Hochzeitsreportage mit Paarshooting am See. Uns wäre wichtig, dass die Stimmung eher ungestellt bleibt.",
    selectedPackages: [{ id: "wedding-8h", name: "Hochzeit Foto 8h", price: "2.490 €", type: "package" }],
    estimatedTotal: "ca. 2.490 €",
  },
  {
    id: "mock-inq-2",
    createdAt: "2026-05-13T08:45:00.000Z",
    status: "beantwortet",
    name: "Miriam Schneider",
    brideName: "",
    groomName: "",
    email: "miriam.schneider@example.com",
    phone: "+49 171 9876543",
    category: "Portrait",
    eventDate: "2026-06-18",
    foundVia: "Google",
    customerAddress: "Höttinger Au 4, 6020 Innsbruck",
    locationAddress: "Hungerburg, Innsbruck",
    locations: [{ id: "loc-portrait", title: "Shooting-Spot", address: "Hungerburg, Innsbruck" }],
    message: "Ich hätte gerne ein ruhiges Outdoor-Portraitshooting in Innsbruck, am liebsten am frühen Abend.",
    selectedPackages: [{ id: "portrait", name: "Portrait Shooting", price: "ab 290 €", type: "package" }],
    estimatedTotal: "ab 290 €",
  },
];

export const mockCustomers = [
  {
    id: "mock-customer-1",
    portalToken: "demo",
    sourceInquiryId: "mock-inq-1",
    createdAt: "2026-05-15T12:00:00.000Z",
    updatedAt: "2026-05-18T08:00:00.000Z",
    status: "vertrag",
    name: "Anna & Lukas Weber",
    brideName: "Anna Weber",
    groomName: "Lukas Weber",
    email: "anna.weber@example.com",
    phone: "+43 660 1234567",
    category: "Hochzeit",
    eventDate: "2026-09-12",
    eventTime: "14:00",
    location: "Seehotel am Achensee, Tirol",
    customerAddress: "Musterstraße 12, 6020 Innsbruck",
    locationAddress: "Seehotel am Achensee, Achenseestraße 10, 6212 Maurach",
    locations: [
      { id: "loc-ceremony", title: "Freie Trauung", address: "Wiese am See, Achensee" },
      { id: "loc-party", title: "Feier", address: "Seehotel am Achensee, Achenseestraße 10, 6212 Maurach" },
    ],
    consultationDate: "22. Mai 2026, 18:30 Uhr · Google Meet",
    consultationType: "Video Call",
    galleryUrl: "",
    offerUrl: "https://marioschub.com/demo/angebot-anna-lukas.pdf",
    contractUrl: "https://marioschub.com/demo/vertrag-anna-lukas.pdf",
    invoiceUrl: "https://marioschub.com/demo/rechnung-anna-lukas.pdf",
    portalEnabled: true,
    portalPassword: "12092026",
    portalPublishedAt: "2026-05-18T08:30:00.000Z",
    contractStatus: "gesendet",
    bookedServices: [
      { id: "wedding-8h", name: "Hochzeitsreportage Foto · 8 Stunden", price: "2.490 €", type: "package" },
      { id: "wedding-guide", name: "Wedding Guide", price: "inklusive", type: "package" },
    ],
    customServices: [
      { id: "custom-travel", name: "Reisekosten Achensee", price: "120 €", type: "custom" },
      { id: "custom-extra", name: "Optionale Zusatzstunde", price: "220 €", type: "custom" },
    ],
    tasks: [
      { id: "task-inquiry", title: "Anfrage beantwortet", status: "erledigt" },
      { id: "task-consult", title: "Vorgespräch terminiert", status: "erledigt" },
      { id: "task-offer", title: "Paket und Add-ons besprochen", status: "erledigt" },
      { id: "task-contract", title: "Vertrag versendet", status: "erledigt" },
      { id: "task-timeline", title: "Ablaufplan/Shotlist anfragen", status: "in_arbeit" },
      { id: "task-gallery", title: "Galerie-Link eintragen", status: "offen" },
    ],
    portalVisibility: {
      status: true,
      tasks: false,
      services: true,
      offer: true,
      contract: true,
      invoice: true,
      gallery: true,
      messages: true,
    },
    portalMessages: [
      {
        id: "msg-1",
        title: "Willkommen im Kundenbereich",
        message: "Ich sammle hier alle wichtigen Links und Infos zu eurer Hochzeit. Sobald etwas fertig ist, schalte ich es gezielt für euch frei.",
        createdAt: "2026-05-18T08:00:00.000Z",
        visible: true,
      },
      {
        id: "msg-2",
        title: "Nächster Schritt",
        message: "Nach dem Vorgespräch ergänze ich hier eure finalen Leistungen und den Ablauf für den Hochzeitstag.",
        createdAt: "2026-05-18T08:15:00.000Z",
        visible: true,
      },
    ],
    notes:
      "Wichtig: eher dokumentarisch, keine gestellten Gruppenbilder im Übermaß. Paarshooting am See kurz vor Golden Hour einplanen. Familie reist aus Deutschland und Österreich an.",
    portalIntro:
      "Hier sammle ich alles Wichtige zu eurer Hochzeit: Termin, Vertrag, Leistungen und später den Link zu eurer finalen Galerie.",
  },
  {
    id: "mock-customer-2",
    portalToken: "portrait-demo",
    sourceInquiryId: "",
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-05-17T16:10:00.000Z",
    status: "vorgespraech",
    name: "Miriam Schneider",
    brideName: "",
    groomName: "",
    email: "miriam.schneider@example.com",
    phone: "+49 171 9876543",
    category: "Portrait",
    eventDate: "2026-06-18",
    eventTime: "18:30",
    location: "Innsbruck Umgebung",
    customerAddress: "Höttinger Au 4, 6020 Innsbruck",
    locationAddress: "Hungerburg, Innsbruck",
    locations: [{ id: "loc-portrait", title: "Shooting-Spot", address: "Hungerburg, Innsbruck" }],
    consultationDate: "20. Mai 2026, 17:00 Uhr · Telefon",
    consultationType: "Telefon",
    galleryUrl: "",
    offerUrl: "",
    contractUrl: "",
    invoiceUrl: "",
    portalEnabled: false,
    portalPassword: "",
    portalPublishedAt: "",
    contractStatus: "nicht_gesendet",
    bookedServices: [{ id: "portrait", name: "Portrait Shooting", price: "ab 290 €", type: "package" }],
    customServices: [],
    tasks: [
      { id: "task-inquiry", title: "Anfrage beantwortet", status: "erledigt" },
      { id: "task-consult", title: "Vorgespräch vorbereiten", status: "in_arbeit" },
      { id: "task-location", title: "Location final abstimmen", status: "offen" },
    ],
    portalVisibility: {
      status: false,
      tasks: false,
      services: true,
      offer: false,
      contract: false,
      invoice: false,
      gallery: true,
      messages: true,
    },
    portalMessages: [
      {
        id: "msg-portrait-1",
        title: "Location-Idee",
        message: "Für die warme Abendstimmung würde Hungerburg oder ein ruhiger Spot am Inn gut passen.",
        createdAt: "2026-05-17T16:10:00.000Z",
        visible: true,
      },
    ],
    notes: "Mood: natürlich, ruhig, nicht zu businesslastig. Sie mag warme Abendstimmung.",
    portalIntro: "Hier findest du alles rund um dein Portraitshooting.",
  },
];
